apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aggregator
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: kornkitti/express-hello-world
          ports:
            - name: http
              containerPort: 8080