apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aggregator
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - port: 3008
      targetPort: http
  selector:
    app: backend