{{- $fullname := $.Values.name}}
{{- with $.Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $fullname }}
spec:
  replicas: {{ .replicas | default 0 }}
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
        - name: {{ $fullname }}
          image: {{ .image }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.targetPort }}
{{- end }}