apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: analytics
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - port: 5008
      targetPort: http
  selector:
    app: backend